from pydantic import BaseModel
from typing import List


class Member(BaseModel):
    wins: str
    losses: str
    otl: str
    winnerByDnf: str
    record: str
    skwins: str
    sklosses: str
    skotl: str
    skwinnerByDnf: str
    skgoals: str
    skassists: str
    skpoints: str
    skpointspg: str
    skgwg: str
    skplusmin: str
    sktoi: str
    skpim: str
    skppg: str
    skshg: str
    skpenaltyshotgoals: str
    skpenaltyattempts: str
    skpenaltyshotpct: str
    skoffsides: str
    skoffsidespg: str
    skfights: str
    skfightswon: str
    skfo: str
    skfow: str
    skfol: str
    skfop: str
    skhits: str
    skhitspg: str
    skbs: str
    skshots: str
    skshotpct: str
    skshotspg: str
    skshotattempts: str
    skshotonnetpct: str
    skpasses: str
    skpassattempts: str
    skpasspct: str
    sksaucerpasses: str
    skdekes: str
    skdekesmade: str
    skgiveaways: str
    sktakeaways: str
    skinterceptions: str
    skscrnchances: str
    skscrngoals: str
    skbrkgoals: str
    skbreakaways: str
    skbreakawaypct: str
    skgc: str
    skgcFC: str
    skhattricks: str
    skprevgoals: str
    skprevassists: str
    skpossession: str
    skdeflections: str
    skpkclearzone: str
    skpenaltiesdrawn: str
    glwins: str
    gllosses: str
    glotl: str
    glwinnerByDnf: str
    glshots: str
    glsaves: str
    glsavepct: str
    gltoi: str
    glga: str
    glgaa: str
    glso: str
    glsoperiods: str
    gldsaves: str
    glbrkshots: str
    glbrksaves: str
    glbrksavepct: str
    glpenshots: str
    glpensaves: str
    glpensavepct: str
    glsoshots: str
    glsosaves: str
    glsosavepct: str
    glrecord: str
    glpokechecks: str
    glgc: str
    glgcFC: str
    glprevwins: str
    glprevso: str
    glpkclearzone: str
    glgp: str
    lwgp: str
    rwgp: str
    cgp: str
    dgp: str
    skgp: str
    gamesplayed: str
    gamesCompleted: str
    gamesCompletedFC: str
    skwinpct: str
    glwinpct: str
    lwQuitDisc: str
    rwQuitDisc: str
    cQuitDisc: str
    dQuitDisc: str
    glQuitDisc: str
    skDNF: str
    lwDNF: str
    rwDNF: str
    cDNF: str
    dDNF: str
    glDNF: str
    glDNFmm: str
    playerQuitDisc: str
    playerDNF: str
    xfactor_zoneability_goals: str
    xfactor_zoneability_assists: str
    xfactor_zoneability_saves: str
    xfactor_zoneability_hits: str
    xfactor_zoneability_stick_checks: str
    xfactor_zoneability_times_used: str
    xfactor_superstarability_goals: str
    xfactor_superstarability_assists: str
    xfactor_superstarability_saves: str
    xfactor_superstarability_hits: str
    xfactor_superstarability_stick_checks: str
    favoritePosition: str
    goals: str
    assists: str
    points: str
    pointspg: str
    gwg: str
    plusmin: str
    toi: str
    pim: str
    ppg: str
    shg: str
    penaltyshotgoals: str
    penaltyattempts: str
    penaltyshotpct: str
    offsides: str
    offsidespg: str
    fights: str
    fightswon: str
    fo: str
    fow: str
    fol: str
    fop: str
    hits: str
    hitspg: str
    bs: str
    shots: str
    shotpct: str
    shotspg: str
    shotattempts: str
    shotonnetpct: str
    passes: str
    passattempts: str
    passpct: str
    saucerpasses: str
    dekes: str
    dekesmade: str
    giveaways: str
    takeaways: str
    interceptions: str
    scrnchances: str
    scrngoals: str
    brkgoals: str
    breakaways: str
    breakawaypct: str
    gc: str
    gcFC: str
    hattricks: str
    prevgoals: str
    prevassists: str
    possession: str
    deflections: str
    pkclearzone: str
    penaltiesdrawn: str
    gp: str
    winpct: str
    DNF: str
    name: str
    clientPlatform: str


class MembersData(BaseModel):
    members: List[Member]
