# .pre-commit-config.yaml
repos:
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.9
        name: black-format
        args: ["--line-length", "120"]  # Customize line length if needed
